name: mindglowequinox
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  email_validator: ^2.1.17
  cloud_firestore: ^4.15.8
  http: ^1.2.0
  video_player: ^2.8.5
  youtube_player_flutter: ^9.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

