// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdqzy5u2to5ywX0mld2Oi3J0Fe8bT76pQ',
    appId: '1:110211076021:web:3a2c940990a6aeebea93fc',
    messagingSenderId: '110211076021',
    projectId: 'mindglow-equinox',
    authDomain: 'mindglow-equinox.firebaseapp.com',
    storageBucket: 'mindglow-equinox.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAFMS_nrUlUK8J-LAR8wbwu53qG6_jwfk',
    appId: '1:110211076021:android:7d2b92c0dd406dacea93fc',
    messagingSenderId: '110211076021',
    projectId: 'mindglow-equinox',
    storageBucket: 'mindglow-equinox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjfUbE6w1-Z_vd2O4E8BIPrLLaQEEBbg0',
    appId: '1:110211076021:ios:2aca8cb3681e20beea93fc',
    messagingSenderId: '110211076021',
    projectId: 'mindglow-equinox',
    storageBucket: 'mindglow-equinox.appspot.com',
    iosBundleId: 'com.example.mindglow',
  );
}
